services:
  r2r:
    image: leesw0924/r2r
    platform: linux/amd64
    ports:
      - 80:8080
    depends_on:
      r2r-db:
        condition: service_healthy
    networks:
      - r2r-network

  r2r-db:
    image: leesw0924/r2rdb
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: r2rdba98!
      MYSQL_DATABASE: r2r
      MYSQL_USER: r2rdba
      MYSQL_PASSWORD: r2rdba98!
    volumes:
      - r2r-volume:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
    networks:
      - r2r-network

networks:
  r2r-network:

volumes:
  r2r-volume: