name: CI/CD for r2r project

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to EC2 and copy docker-compose file
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.R2R_EC2_HOST }}  # EC2 서버의 호스트 주소
          username: ${{ secrets.R2R_EC2_USERNAME }}  # EC2 서버의 사용자 이름
          key: ${{ secrets.R2R_EC2_PRIVATE_KEY }}  # EC2 접속에 사용할 개인 키
          source: ./compose.yml  # 로컬 레포지토리의 docker-compose.yml 파일
          target: /home/ubuntu/r2r/compose.yml  # EC2 서버의 대상 경로

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.R2R_EC2_HOST }}  # EC2 서버의 호스트 주소
          username: ${{ secrets.R2R_EC2_USERNAME }}  # EC2 서버의 사용자 이름
          key: ${{ secrets.R2R_EC2_PRIVATE_KEY }}  # EC2 접속에 사용할 개인 키
          script: |
            cd /home/ubuntu/r2r
            docker compose down
            docker compose pull
            docker compose up -d