name: CI/CD for r2r

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: ./SpringBoot  # SpringBoot 디렉터리에서 빌드 실행

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # SpringBoot 애플리케이션 이미지 빌드 및 푸시
    - name: Build and push r2r image
      run: |
        docker build -t leesw0924/r2r ./SpringBoot/
        docker push leesw0924/r2r

    # MySQL 이미지 빌드 및 푸시
    - name: Build and push MySQL image
      run: |
        docker build -t leesw0924/r2r-mysql ./mysql/
        docker push leesw0924/r2r-mysql

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.R2R_EC2_HOST }}
        username: ${{ secrets.R2R_EC2_USERNAME }}
        key: ${{ secrets.R2R_EC2_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/r2r
          docker-compose down
          docker-compose pull
          docker-compose up -d