name: CI/CD for r2r project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to EC2 and copy docker-compose file
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.R2R_EC2_HOST }}
          username: ${{ secrets.R2R_EC2_USERNAME }}
          key: ${{ secrets.R2R_EC2_PRIVATE_KEY }}
          source: ./compose.yml
          target: /home/ubuntu/r2r/compose.yml
          overwrite: true #d

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.R2R_EC2_HOST }}
          username: ${{ secrets.R2R_EC2_USERNAME }}
          key: ${{ secrets.R2R_EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/r2r
            docker compose -f compose.yml down
            docker compose -f compose.yml pull
            docker compose -f compose.yml up -d